# Generated by Django 4.2.27 on 2026-02-03 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('norma', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('procedimento', 'Procedimento'), ('instrucao', 'Instrução'), ('registro', 'Registro')], max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Arquivo do Documento')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20)),
                ('proxima_calibracao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='padroes/certificados/', verbose_name='Certificado do Padrão')),
                ('status', models.CharField(choices=[('valido', 'Válido'), ('vencido', 'Vencido'), ('suspenso', 'Suspenso')], default='valido', max_length=20)),
                ('vencimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('calibracao', 'Calibração'), ('manutencao', 'Manutenção')], max_length=20)),
                ('intervalo_meses', models.PositiveIntegerField(help_text='Intervalo em meses')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodicidades', to='calibracao.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_medicao', models.CharField(blank=True, max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('classe', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to='calibracao.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='Calibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('os_cliente', models.CharField(blank=True, max_length=50, verbose_name='OS do Cliente')),
                ('instrumento_critico', models.BooleanField(default=False, verbose_name='Instrumento Crítico')),
                ('condicao_uso', models.BooleanField(default=True, verbose_name='Instrumento em condição de uso')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa executante')),
                ('local_instalacao', models.CharField(blank=True, max_length=150)),
                ('local_armazenamento', models.CharField(blank=True, max_length=150)),
                ('sub_local', models.CharField(blank=True, max_length=150)),
                ('data_calibracao', models.DateField()),
                ('validade', models.DateField(blank=True, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='calibracoes/certificados/')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes', to='calibracao.instrumento')),
            ],
        ),
    ]
