# Generated by Django 4.2.27 on 2026-02-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
